---
- name: install docker and configure
  hosts: _development
  become: true
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: "*"
        state: latest

    - name: remove old docker packages
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: install yum utils
      ansible.builtin.yum:
        name: "yum-utils"
        state: latest

    - name: add docker repo
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: install docker
      ansible.builtin.package: 
        name: "docker-ce"
        state: latest

    - name: add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        group: docker
        append: yes

    - name: start docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

- name: configure postgre instance
  hosts: _ansible_postgresql
  become: true
  vars_files:
    - secret.yml
  vars:
    container_path: /home/ec2-user/postgresql
    container_name: kubi_postgre
    image_name: kubi/postgre
  tasks:
    - name: copy files to the postgresql node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/postgres/
        dest: "{{ container_path }}"

    - name: remove kubi_postgre container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true
        
    - name: remove kubi_postgre image
      docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: build docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: "{{ container_path }}"
        source: build
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info
      
    - name: run postgresql docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "{{password}}"
        volumes:
          - /db-data:/var/lib/postgresql/data
      register: container_info

    - name: print the container info
      ansible.builtin.debug:
        var: container_info

- name: nodejs configuration
  hosts: _ansible_nodejs
  become: true
  vars:
    container_path: /home/ec2-user/nodejs
    container_name: kubi_nodejs
    image_name: kubi/nodejs
  tasks:
    - name: copy files to the nodejs node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/nodejs/
        dest: "{{ container_path }}"

    - name: remove kubi_nodejs container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: remove kubi/nodejs image
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: build docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: build
        build:
          path: /home/ec2-user/nodejs
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: run nodejs docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "5000:5000"
      register: container_info

    - name: print the container info
      ansible.builtin.debug:
        var: container_info

- name: React UI Server Configuration
  hosts: _ansible_react
  become: true
  vars:
    container_path: /home/ec2-user/react
    container_name: kubi_react
    image_name: kubi/react
  tasks:
    - name: copy files to the react node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/react/
        dest: "{{ container_path }}"

    - name: remove kubi_react container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
        force_kill: true

    - name: remove kubi/react image
      community.docker.docker_image:
        name: "{{ image_name }}"
        state: absent

    - name: build docker image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: build
        build:
          path: /home/ec2-user/react
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: run react docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}"
        state: started
        ports:
          - "3000:3000"
      register: container_info

    - name: print the container info
      ansible.builtin.debug:
        var: container_info